export type CardRarity = 'Common' | 'Rare' | 'Epic' | 'Legendary' | 'Mythic';

export type CardElement =
  | 'fire'
  | 'water'
  | 'earth'
  | 'air'
  | 'light'
  | 'shadow'
  | 'nature'
  | 'arcane';

export type CardKind =
  | 'beast'
  | 'humanoid'
  | 'spirit'
  | 'undead'
  | 'dragon'
  | 'demon'
  | 'construct'
  | 'mythic';

export type CardAbility = {
  key: 'basic' | 'skill';
  name: string;
  kind: 'damage' | 'heal' | 'shield' | 'dot' | 'stun';
  power: number; // масштаб урона/хила относительно card.power
  cooldownTurns: number;
};

export type CharacterCard = {
  id: string;
  name: string;
  rarity: CardRarity;
  element: CardElement;
  kind: CardKind;
  hp: number;
  power: number;
  speed: number; // 1..10, пригодится для инициативы позже
  abilities: [CardAbility, CardAbility];
};

function A(
  key: 'basic' | 'skill',
  name: string,
  kind: CardAbility['kind'],
  power: number,
  cooldownTurns: number
): CardAbility {
  return { key, name, kind, power, cooldownTurns };
}

/**
 * Каталог из 60 персонажей:
 * - 30 Common
 * - 15 Rare
 * - 9 Epic
 * - 4 Legendary
 * - 2 Mythic
 *
 * Числа HP/Power сбалансированы под быстрые бои 3×3 (можно тюнить).
 */
export const CHARACTER_CARDS: CharacterCard[] = [
  // ===== COMMON (1..30) =====
  {
    id: 'c001_field-mouse',
    name: 'Полевая мышь',
    rarity: 'Common',
    element: 'nature',
    kind: 'beast',
    hp: 220,
    power: 18,
    speed: 8,
    abilities: [A('basic', 'Укус', 'damage', 0.95, 0), A('skill', 'Рывок в траву', 'shield', 0.7, 2)],
  },
  {
    id: 'c002_sparrow',
    name: 'Воробей-скаут',
    rarity: 'Common',
    element: 'air',
    kind: 'beast',
    hp: 200,
    power: 19,
    speed: 9,
    abilities: [A('basic', 'Клюв', 'damage', 0.9, 0), A('skill', 'Воздушная тревога', 'shield', 0.75, 3)],
  },
  {
    id: 'c003_hedgehog',
    name: 'Ёж-щит',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 310,
    power: 16,
    speed: 5,
    abilities: [A('basic', 'Игольчатый таран', 'damage', 0.9, 0), A('skill', 'Свернуться', 'shield', 1.05, 3)],
  },
  {
    id: 'c004_rabbit',
    name: 'Лесной заяц',
    rarity: 'Common',
    element: 'nature',
    kind: 'beast',
    hp: 240,
    power: 17,
    speed: 8,
    abilities: [A('basic', 'Пинок', 'damage', 0.85, 0), A('skill', 'Рваный след', 'heal', 0.8, 3)],
  },
  {
    id: 'c005_wolf-cub',
    name: 'Волчонок',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 280,
    power: 20,
    speed: 7,
    abilities: [A('basic', 'Когти', 'damage', 1.0, 0), A('skill', 'Вой стаи', 'damage', 1.25, 3)],
  },
  {
    id: 'c006_boar',
    name: 'Кабан-разрушитель',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 340,
    power: 19,
    speed: 5,
    abilities: [A('basic', 'Наскок', 'damage', 0.95, 0), A('skill', 'Железный лоб', 'shield', 0.95, 3)],
  },
  {
    id: 'c007_falcon',
    name: 'Сокол',
    rarity: 'Common',
    element: 'air',
    kind: 'beast',
    hp: 230,
    power: 21,
    speed: 9,
    abilities: [A('basic', 'Пикирование', 'damage', 1.0, 0), A('skill', 'Разрез крыла', 'damage', 1.35, 3)],
  },
  {
    id: 'c008_fox',
    name: 'Лиса-хитрюга',
    rarity: 'Common',
    element: 'air',
    kind: 'beast',
    hp: 250,
    power: 19,
    speed: 8,
    abilities: [A('basic', 'Укол лапой', 'damage', 0.9, 0), A('skill', 'Ложная цель', 'shield', 0.85, 3)],
  },
  {
    id: 'c009_bear',
    name: 'Медведь',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 420,
    power: 18,
    speed: 4,
    abilities: [A('basic', 'Лапа', 'damage', 0.95, 0), A('skill', 'Рык', 'stun', 0.55, 4)],
  },
  {
    id: 'c010_owl',
    name: 'Сова-провидец',
    rarity: 'Common',
    element: 'arcane',
    kind: 'beast',
    hp: 240,
    power: 18,
    speed: 7,
    abilities: [A('basic', 'Тёмный клюв', 'damage', 0.9, 0), A('skill', 'Предвидение', 'shield', 0.85, 3)],
  },
  {
    id: 'c011_snake',
    name: 'Змея',
    rarity: 'Common',
    element: 'shadow',
    kind: 'beast',
    hp: 230,
    power: 20,
    speed: 8,
    abilities: [A('basic', 'Укус', 'damage', 0.9, 0), A('skill', 'Яд', 'dot', 0.85, 3)],
  },
  {
    id: 'c012_stag',
    name: 'Олень',
    rarity: 'Common',
    element: 'nature',
    kind: 'beast',
    hp: 300,
    power: 18,
    speed: 6,
    abilities: [A('basic', 'Рога', 'damage', 0.9, 0), A('skill', 'Лесное исцеление', 'heal', 1.05, 4)],
  },
  {
    id: 'c013_crab',
    name: 'Краб-камень',
    rarity: 'Common',
    element: 'water',
    kind: 'beast',
    hp: 330,
    power: 16,
    speed: 4,
    abilities: [A('basic', 'Клешни', 'damage', 0.85, 0), A('skill', 'Панцирь', 'shield', 1.1, 3)],
  },
  {
    id: 'c014_piranha',
    name: 'Пиранья',
    rarity: 'Common',
    element: 'water',
    kind: 'beast',
    hp: 220,
    power: 21,
    speed: 8,
    abilities: [A('basic', 'Рваный укус', 'damage', 0.95, 0), A('skill', 'Кровь в воде', 'damage', 1.35, 3)],
  },
  {
    id: 'c015_tortoise',
    name: 'Черепаха',
    rarity: 'Common',
    element: 'water',
    kind: 'beast',
    hp: 380,
    power: 15,
    speed: 3,
    abilities: [A('basic', 'Тяжёлый удар', 'damage', 0.85, 0), A('skill', 'Под панцирь', 'shield', 1.2, 4)],
  },
  {
    id: 'c016_mantis',
    name: 'Богомол',
    rarity: 'Common',
    element: 'nature',
    kind: 'beast',
    hp: 230,
    power: 22,
    speed: 8,
    abilities: [A('basic', 'Срез', 'damage', 1.0, 0), A('skill', 'Двойной разрез', 'damage', 1.55, 3)],
  },
  {
    id: 'c017_bat',
    name: 'Летучая мышь',
    rarity: 'Common',
    element: 'shadow',
    kind: 'beast',
    hp: 210,
    power: 20,
    speed: 9,
    abilities: [A('basic', 'Писк', 'damage', 0.85, 0), A('skill', 'Кража силы', 'heal', 0.75, 3)],
  },
  {
    id: 'c018_goat',
    name: 'Горный козёл',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 290,
    power: 18,
    speed: 6,
    abilities: [A('basic', 'Удар рогами', 'damage', 0.9, 0), A('skill', 'Скальная стойка', 'shield', 1.0, 3)],
  },
  {
    id: 'c019_hyena',
    name: 'Гиена',
    rarity: 'Common',
    element: 'shadow',
    kind: 'beast',
    hp: 260,
    power: 21,
    speed: 7,
    abilities: [A('basic', 'Зубы', 'damage', 0.95, 0), A('skill', 'Злобный смех', 'stun', 0.55, 3)],
  },
  {
    id: 'c020_salamander',
    name: 'Саламандра',
    rarity: 'Common',
    element: 'fire',
    kind: 'beast',
    hp: 250,
    power: 20,
    speed: 7,
    abilities: [A('basic', 'Ожог', 'damage', 0.9, 0), A('skill', 'Пламя хвоста', 'dot', 0.9, 3)],
  },
  {
    id: 'c021_iguanodon',
    name: 'Игуанодон',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 410,
    power: 17,
    speed: 3,
    abilities: [A('basic', 'Топот', 'damage', 0.9, 0), A('skill', 'Давка', 'damage', 1.35, 4)],
  },
  {
    id: 'c022_fire-dog',
    name: 'Пёс углей',
    rarity: 'Common',
    element: 'fire',
    kind: 'beast',
    hp: 270,
    power: 20,
    speed: 7,
    abilities: [A('basic', 'Укус жара', 'damage', 0.95, 0), A('skill', 'Огненный рывок', 'damage', 1.35, 3)],
  },
  {
    id: 'c023_river-frog',
    name: 'Речная лягушка',
    rarity: 'Common',
    element: 'water',
    kind: 'beast',
    hp: 240,
    power: 17,
    speed: 7,
    abilities: [A('basic', 'Хлёсткий язык', 'damage', 0.85, 0), A('skill', 'Пузырьки', 'heal', 0.85, 3)],
  },
  {
    id: 'c024_black-cat',
    name: 'Чёрная кошка',
    rarity: 'Common',
    element: 'shadow',
    kind: 'beast',
    hp: 235,
    power: 21,
    speed: 9,
    abilities: [A('basic', 'Царапины', 'damage', 0.95, 0), A('skill', 'Прыжок в тень', 'stun', 0.6, 3)],
  },
  {
    id: 'c025_white-stag',
    name: 'Белый олень',
    rarity: 'Common',
    element: 'light',
    kind: 'spirit',
    hp: 290,
    power: 18,
    speed: 6,
    abilities: [A('basic', 'Световой удар', 'damage', 0.9, 0), A('skill', 'Луч надежды', 'heal', 1.0, 4)],
  },
  {
    id: 'c026_raccoon',
    name: 'Енот-вор',
    rarity: 'Common',
    element: 'air',
    kind: 'beast',
    hp: 245,
    power: 19,
    speed: 8,
    abilities: [A('basic', 'Шлепок', 'damage', 0.85, 0), A('skill', 'Украденная аптечка', 'heal', 0.85, 3)],
  },
  {
    id: 'c027_snow-hare',
    name: 'Снежный заяц',
    rarity: 'Common',
    element: 'water',
    kind: 'beast',
    hp: 250,
    power: 18,
    speed: 8,
    abilities: [A('basic', 'Холодный пинок', 'damage', 0.85, 0), A('skill', 'Ледяной щит', 'shield', 0.95, 3)],
  },
  {
    id: 'c028_crow',
    name: 'Ворон',
    rarity: 'Common',
    element: 'shadow',
    kind: 'beast',
    hp: 230,
    power: 20,
    speed: 8,
    abilities: [A('basic', 'Клюв', 'damage', 0.9, 0), A('skill', 'Метка падальщика', 'dot', 0.8, 3)],
  },
  {
    id: 'c029_mole',
    name: 'Крот',
    rarity: 'Common',
    element: 'earth',
    kind: 'beast',
    hp: 320,
    power: 16,
    speed: 5,
    abilities: [A('basic', 'Копать', 'damage', 0.85, 0), A('skill', 'Подземный уход', 'shield', 1.05, 4)],
  },
  {
    id: 'c030_koi',
    name: 'Карп кои',
    rarity: 'Common',
    element: 'water',
    kind: 'spirit',
    hp: 260,
    power: 17,
    speed: 6,
    abilities: [A('basic', 'Всплеск', 'damage', 0.85, 0), A('skill', 'Поток удачи', 'heal', 0.95, 4)],
  },

  // ===== RARE (31..45) =====
  {
    id: 'r031_dire-wolf',
    name: 'Лютоволк',
    rarity: 'Rare',
    element: 'earth',
    kind: 'beast',
    hp: 520,
    power: 28,
    speed: 7,
    abilities: [A('basic', 'Раздирание', 'damage', 1.0, 0), A('skill', 'Лунная ярость', 'damage', 1.6, 3)],
  },
  {
    id: 'r032_phoenix-chick',
    name: 'Птенец феникса',
    rarity: 'Rare',
    element: 'fire',
    kind: 'spirit',
    hp: 440,
    power: 27,
    speed: 8,
    abilities: [A('basic', 'Искры', 'damage', 0.95, 0), A('skill', 'Перерождение', 'heal', 1.35, 4)],
  },
  {
    id: 'r033_ice-lynx',
    name: 'Ледяная рысь',
    rarity: 'Rare',
    element: 'water',
    kind: 'beast',
    hp: 470,
    power: 29,
    speed: 9,
    abilities: [A('basic', 'Когти льда', 'damage', 1.0, 0), A('skill', 'Заморозка', 'stun', 0.7, 3)],
  },
  {
    id: 'r034_griffin',
    name: 'Грифон',
    rarity: 'Rare',
    element: 'air',
    kind: 'mythic',
    hp: 500,
    power: 30,
    speed: 8,
    abilities: [A('basic', 'Срыв', 'damage', 1.0, 0), A('skill', 'Крылья прикрытия', 'shield', 1.25, 3)],
  },
  {
    id: 'r035_bone-hound',
    name: 'Костяная гончая',
    rarity: 'Rare',
    element: 'shadow',
    kind: 'undead',
    hp: 480,
    power: 30,
    speed: 7,
    abilities: [A('basic', 'Грызть кость', 'damage', 0.95, 0), A('skill', 'Проклятый укус', 'dot', 1.05, 3)],
  },
  {
    id: 'r036_stone-golem',
    name: 'Каменный голем',
    rarity: 'Rare',
    element: 'earth',
    kind: 'construct',
    hp: 720,
    power: 25,
    speed: 3,
    abilities: [A('basic', 'Каменный удар', 'damage', 0.95, 0), A('skill', 'Гранитная кожа', 'shield', 1.55, 4)],
  },
  {
    id: 'r037_mystic-serpent',
    name: 'Мистический змей',
    rarity: 'Rare',
    element: 'arcane',
    kind: 'spirit',
    hp: 460,
    power: 29,
    speed: 8,
    abilities: [A('basic', 'Эфирный укус', 'damage', 0.95, 0), A('skill', 'Сонная спираль', 'stun', 0.7, 4)],
  },
  {
    id: 'r038_sun-paladin',
    name: 'Солнечный паладин',
    rarity: 'Rare',
    element: 'light',
    kind: 'humanoid',
    hp: 560,
    power: 27,
    speed: 6,
    abilities: [A('basic', 'Световой клинок', 'damage', 1.0, 0), A('skill', 'Аура защиты', 'shield', 1.25, 3)],
  },
  {
    id: 'r039_moon-witch',
    name: 'Лунная ведьма',
    rarity: 'Rare',
    element: 'arcane',
    kind: 'humanoid',
    hp: 430,
    power: 32,
    speed: 7,
    abilities: [A('basic', 'Чары', 'damage', 0.95, 0), A('skill', 'Лунный сглаз', 'dot', 1.15, 3)],
  },
  {
    id: 'r040_swamp-troll',
    name: 'Болотный тролль',
    rarity: 'Rare',
    element: 'nature',
    kind: 'humanoid',
    hp: 650,
    power: 26,
    speed: 4,
    abilities: [A('basic', 'Дубина', 'damage', 0.95, 0), A('skill', 'Регенерация', 'heal', 1.4, 4)],
  },
  {
    id: 'r041_sand-assassin',
    name: 'Песчаный ассасин',
    rarity: 'Rare',
    element: 'air',
    kind: 'humanoid',
    hp: 450,
    power: 31,
    speed: 9,
    abilities: [A('basic', 'Укол', 'damage', 1.0, 0), A('skill', 'Песчаная пелена', 'stun', 0.75, 4)],
  },
  {
    id: 'r042_forest-ent',
    name: 'Древень-энт',
    rarity: 'Rare',
    element: 'nature',
    kind: 'mythic',
    hp: 700,
    power: 25,
    speed: 3,
    abilities: [A('basic', 'Лоза', 'damage', 0.9, 0), A('skill', 'Кора', 'shield', 1.6, 4)],
  },
  {
    id: 'r043_wisp',
    name: 'Блуждающий огонёк',
    rarity: 'Rare',
    element: 'light',
    kind: 'spirit',
    hp: 380,
    power: 33,
    speed: 10,
    abilities: [A('basic', 'Луч', 'damage', 0.95, 0), A('skill', 'Путеводный свет', 'heal', 1.15, 3)],
  },
  {
    id: 'r044_shadow-stalker',
    name: 'Теневой преследователь',
    rarity: 'Rare',
    element: 'shadow',
    kind: 'spirit',
    hp: 430,
    power: 32,
    speed: 9,
    abilities: [A('basic', 'Теневой разрез', 'damage', 1.0, 0), A('skill', 'Поглощение', 'heal', 1.1, 4)],
  },
  {
    id: 'r045_storm-rider',
    name: 'Всадник бури',
    rarity: 'Rare',
    element: 'air',
    kind: 'humanoid',
    hp: 510,
    power: 29,
    speed: 8,
    abilities: [A('basic', 'Громовой удар', 'damage', 1.0, 0), A('skill', 'Попутный ветер', 'shield', 1.2, 3)],
  },

  // ===== EPIC (46..54) =====
  {
    id: 'e046_ancient-drake',
    name: 'Древний дрейк',
    rarity: 'Epic',
    element: 'fire',
    kind: 'dragon',
    hp: 980,
    power: 44,
    speed: 5,
    abilities: [A('basic', 'Когти дракона', 'damage', 1.05, 0), A('skill', 'Огненное дыхание', 'dot', 1.4, 3)],
  },
  {
    id: 'e047_frost-giant',
    name: 'Ледяной великан',
    rarity: 'Epic',
    element: 'water',
    kind: 'humanoid',
    hp: 1100,
    power: 40,
    speed: 3,
    abilities: [A('basic', 'Ледяной молот', 'damage', 1.0, 0), A('skill', 'Ледяная стена', 'shield', 1.7, 4)],
  },
  {
    id: 'e048_lich-scholar',
    name: 'Лич-учёный',
    rarity: 'Epic',
    element: 'shadow',
    kind: 'undead',
    hp: 820,
    power: 48,
    speed: 6,
    abilities: [A('basic', 'Некро-луч', 'damage', 1.0, 0), A('skill', 'Чума', 'dot', 1.55, 3)],
  },
  {
    id: 'e049_seraph-guardian',
    name: 'Серафим-страж',
    rarity: 'Epic',
    element: 'light',
    kind: 'spirit',
    hp: 920,
    power: 43,
    speed: 7,
    abilities: [A('basic', 'Световой удар', 'damage', 1.0, 0), A('skill', 'Небесный барьер', 'shield', 1.65, 4)],
  },
  {
    id: 'e050_archdruid',
    name: 'Архидруид',
    rarity: 'Epic',
    element: 'nature',
    kind: 'humanoid',
    hp: 880,
    power: 45,
    speed: 6,
    abilities: [A('basic', 'Шипы', 'damage', 1.0, 0), A('skill', 'Великий рост', 'heal', 1.75, 4)],
  },
  {
    id: 'e051_void-sentinel',
    name: 'Страж Пустоты',
    rarity: 'Epic',
    element: 'arcane',
    kind: 'construct',
    hp: 930,
    power: 44,
    speed: 5,
    abilities: [A('basic', 'Импульс', 'damage', 1.0, 0), A('skill', 'Пустотный щит', 'shield', 1.55, 4)],
  },
  {
    id: 'e052_demon-duelist',
    name: 'Демон-дуэлянт',
    rarity: 'Epic',
    element: 'shadow',
    kind: 'demon',
    hp: 860,
    power: 47,
    speed: 9,
    abilities: [A('basic', 'Клинок греха', 'damage', 1.05, 0), A('skill', 'Адский выпад', 'damage', 1.85, 3)],
  },
  {
    id: 'e053_thunder-roc',
    name: 'Громовой рок',
    rarity: 'Epic',
    element: 'air',
    kind: 'mythic',
    hp: 900,
    power: 45,
    speed: 8,
    abilities: [A('basic', 'Удар крыла', 'damage', 1.0, 0), A('skill', 'Грозовое прикрытие', 'shield', 1.55, 4)],
  },
  {
    id: 'e054_magma-titan',
    name: 'Магмовый титан',
    rarity: 'Epic',
    element: 'fire',
    kind: 'construct',
    hp: 1200,
    power: 39,
    speed: 2,
    abilities: [A('basic', 'Камнепад', 'damage', 1.0, 0), A('skill', 'Магмовый панцирь', 'shield', 1.9, 4)],
  },

  // ===== LEGENDARY (55..58) =====
  {
    id: 'l055_celestial-dragon',
    name: 'Небесный дракон',
    rarity: 'Legendary',
    element: 'light',
    kind: 'dragon',
    hp: 1550,
    power: 62,
    speed: 6,
    abilities: [A('basic', 'Сияющие когти', 'damage', 1.05, 0), A('skill', 'Небесное благословение', 'heal', 1.85, 4)],
  },
  {
    id: 'l056_abyss-hydra',
    name: 'Гидра бездны',
    rarity: 'Legendary',
    element: 'shadow',
    kind: 'dragon',
    hp: 1680,
    power: 60,
    speed: 5,
    abilities: [A('basic', 'Укус голов', 'damage', 1.05, 0), A('skill', 'Яд гидры', 'dot', 2.0, 4)],
  },
  {
    id: 'l057_arcane-sphinx',
    name: 'Арканная сфинкса',
    rarity: 'Legendary',
    element: 'arcane',
    kind: 'mythic',
    hp: 1450,
    power: 63,
    speed: 7,
    abilities: [A('basic', 'Загадка', 'damage', 1.05, 0), A('skill', 'Печать разума', 'stun', 1.2, 4)],
  },
  {
    id: 'l058_world-tree-avatar',
    name: 'Аватар Древа Миров',
    rarity: 'Legendary',
    element: 'nature',
    kind: 'mythic',
    hp: 1750,
    power: 56,
    speed: 3,
    abilities: [A('basic', 'Корни', 'damage', 1.0, 0), A('skill', 'Жизненный прилив', 'heal', 2.1, 4)],
  },

  // ===== MYTHIC (59..60) =====
  {
    id: 'm059_primordial-phoenix',
    name: 'Первородный феникс',
    rarity: 'Mythic',
    element: 'fire',
    kind: 'mythic',
    hp: 2100,
    power: 78,
    speed: 8,
    abilities: [A('basic', 'Пепельный клинок', 'damage', 1.1, 0), A('skill', 'Супернова', 'damage', 2.6, 5)],
  },
  {
    id: 'm060_astral-leviathan',
    name: 'Астральный левиафан',
    rarity: 'Mythic',
    element: 'water',
    kind: 'mythic',
    hp: 2400,
    power: 74,
    speed: 4,
    abilities: [A('basic', 'Прилив', 'damage', 1.1, 0), A('skill', 'Астральный прилив', 'heal', 2.2, 5)],
  },
];

